# --- Site Identity ---
title: Zendly AI Tools
email: hello@zendly.ai
description: >-
  Discover the best free and paid AI tools to automate your small business — from invoicing and support to websites and emails.
author: Zendly AI
url: "https://zendly94.github.io"
baseurl: ""  # Leave blank for GitHub Pages root

# --- Appearance ---
avatar: https://github.com/Zendly94/Zendly94.github.io/blob/master/2a49cc1f-593c-44d2-863f-1dc402b78a15.png
theme: jekyll-theme-minimal
show_downloads: false

# --- Social (optional) ---
twitter_username: ""
github_username: Zendly94

# --- Navigation ---
links:
  - title: Home
    url: /
  - title: Blog
    url: /archive/
  - title: Tools
    url: /tools/
  - title: About
    url: /about/

# --- SEO / Meta ---
permalink: /:year/:month/:day/:title.html
markdown: kramdown
kramdown:
  input: GFM

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# --- Google Analytics (optional) ---
google_analytics: ""
